# Generated by Django 3.2.8 on 2021-11-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id_aset', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('status_aset', models.CharField(choices=[('B', 'Baik'), ('KB', 'Kurang Baik'), ('RB', 'Rusak Berat')], default='B', max_length=2)),
                ('nama_aset', models.CharField(max_length=50)),
                ('no', models.IntegerField()),
                ('no_register', models.CharField(max_length=20)),
                ('tahun_perolehan', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('asal_usul', models.CharField(max_length=50)),
                ('keterangan_mutasi', models.TextField()),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Klasifikasi_aset',
            fields=[
                ('id_klasifikasi', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nama_klasifikasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kode_kelompok',
            fields=[
                ('id_kelompok', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_kelompok', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi_aset',
            fields=[
                ('id_lokasi', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nama_lokasi', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kiba',
            fields=[
                ('id_aset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kiba', serialize=False, to='aset.aset')),
                ('luas', models.FloatField(max_length=10)),
                ('hak_tanah', models.CharField(max_length=50)),
                ('tanggal_sertifikat', models.DateField(null=True)),
                ('no_sertifikat', models.CharField(max_length=50)),
                ('penggunaan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kibb',
            fields=[
                ('id_aset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kibb', serialize=False, to='aset.aset')),
                ('merek', models.CharField(max_length=100)),
                ('ukuran', models.CharField(max_length=50)),
                ('bahan', models.CharField(max_length=50)),
                ('no_pabrik', models.CharField(max_length=50)),
                ('no_rangka', models.CharField(max_length=50)),
                ('no_mesin', models.CharField(max_length=50)),
                ('no_polisi', models.CharField(max_length=30)),
                ('no_bpkb', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kibc',
            fields=[
                ('id_aset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kibc', serialize=False, to='aset.aset')),
                ('kontruksi_bertingkat', models.BooleanField()),
                ('kontruksi_beton', models.BooleanField()),
                ('luas_lantai', models.FloatField(max_length=10)),
                ('tanggal_dokumen_gedung', models.DateField(null=True)),
                ('no_dokumen_gedung', models.CharField(max_length=40)),
                ('luas', models.FloatField(max_length=10)),
                ('status_tanah', models.CharField(max_length=50)),
                ('no_kode_tanah', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kibd',
            fields=[
                ('id_aset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kibd', serialize=False, to='aset.aset')),
                ('judul_buku', models.CharField(max_length=50)),
                ('spesifikasi_buku', models.CharField(max_length=50)),
                ('asal_daerah_kesenian', models.CharField(max_length=50)),
                ('pencipta_kesenian', models.CharField(max_length=50)),
                ('bahan_kesenian', models.CharField(max_length=70)),
                ('jenis_hewan', models.CharField(max_length=50)),
                ('ukuran_hewan', models.IntegerField()),
                ('jumlah_hewan', models.IntegerField()),
                ('tahun_cetak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id_ruang', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_ruang', models.CharField(max_length=50)),
                ('id_kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kode_kelompok')),
                ('id_lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.lokasi_aset')),
            ],
        ),
        migrations.CreateModel(
            name='Jenis_aset',
            fields=[
                ('id_jenis', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50)),
                ('id_klasifikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.klasifikasi_aset')),
            ],
        ),
        migrations.AddField(
            model_name='aset',
            name='id_jenis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.jenis_aset'),
        ),
        migrations.AddField(
            model_name='aset',
            name='id_ruangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.ruangan'),
        ),
        migrations.CreateModel(
            name='Detail_kelompok_aset',
            fields=[
                ('id_kelompok_aset', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.aset')),
                ('id_kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kode_kelompok')),
            ],
            options={
                'unique_together': {('id_kelompok', 'id_aset')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aset',
            unique_together={('id_jenis', 'id_ruangan', 'tahun_perolehan', 'no')},
        ),
    ]
