# Generated by Django 3.2.8 on 2021-11-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aset',
            name='keterangan_mutasi',
        ),
        migrations.DeleteModel(
            name='Detail_kelompok_aset',
        ),
    ]
