# Generated by Django 3.2.8 on 2021-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0002_auto_20211123_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='harga',
            field=models.FloatField(max_length=10),
        ),
    ]
