# Generated by Django 3.2.8 on 2021-12-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0003_alter_aset_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
